#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 29 18:01:15 2018

@author: cariello
"""

import surprise

import numpy as np
import pandas as pd

work="~/desenv/rcm-portal/dados"
input_csv = r"%s/id_menu+id_usuario+mean_score.csv" % work

inputDf = pd.read_csv(input_csv, delimiter=";")

x = inputDf[['userId', 'itemId']].groupby(['userId']).agg(['count'])

y = x['itemId']

y['userId'] = y.index

z = y[ y[ 'count' ] >= 10]

df = inputDf.merge(z, on=['userId'])

del df['count']

df['adjustedScore'] = 0

def adjustedScoreFn(row):
    if(row['score'] > .8):
        return 1
    if(row['score'] > .5):
        return .5
    if(row['score'] > .3):
        return .3
    
    return 0


df.apply (lambda row: adjustedScoreFn(row))




y = x[ x['(itemId, count)'] > 5  ]

common = df.merge(x, on=['userId','userId'])

lower_rating = df['score'].min()
upper_rating = df['score'].max()

print('Score range: {0} to {1}'.format(lower_rating, upper_rating))

reader = surprise.Reader(rating_scale= (lower_rating, upper_rating))
data = surprise.Dataset.load_from_df(df, reader)

alg = surprise.SVDpp()
output = alg.fit(data.build_full_trainset())

pred = alg.predict(uid='32', iid='649')
score = pred.est
print(score)

#All item ids
iids = df['itemId'].unique()

#iids of uid=32
iid32 = df.loc[df['userId'] == 32, 'itemId']

iids_to_pred = np.setdiff1d(iids, iid32)

#now, predict the items userId 32 didnt rate and find the top 10
testset = [ [32,iid, upper_rating] for iid in iids_to_pred]
predictions = alg.test(testset)
predictions[0]

pred_ratings = np.array([pred.est for pred in predictions])

i_max = pred_ratings.argmax()

iid = iids_to_pred[i_max]
print('Top item for user 50 has iid {0} with predicted rating {1}'.format(iid, pred_ratings[i_max] ))

ind = np.argpartition(pred_ratings, -10)[-10:]

for i in ind:
    print('Estimative rating for item {0} is {1}'.format(i, pred_ratings[i]))
    
    
param_grid = {'lr_all' : [.00001, .01], 'reg_all' : [.0001, .5]}
gs = surprise.model_selection.GridSearchCV(surprise.SVDpp, param_grid, measures=['rmse', 'mae'], cv=3)
gs.fit(data)

print( gs.best_params['rmse'] )

alg = surprise.SVDpp(lr_all = .01)
output = surprise.model_selection.cross_validate(alg, data, verbose = True)